project: 
  type: website 
  output-dir: docs 

website:
  title: "Final Project" 
  navbar: 
    left: 
    
    - Home.qmd
    - Project Details.qmd
    - Research Design.qmd
    - fp.qmd
    - Conclusion.qmd

format: 
  html: 
    theme: Flatly